version: '3'
services:
  db:
    image: postgres
    restart: always
    container_name: coffee
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: jobsboard
